### ISSUE TITLE
Changing theme

### ISSUE THREAD

**Issue by VeraRibeiro** [underfisk/apollo-spreadsheet#29]
Issue in apollo grid when changing theme

When we switch from light to dark mode, apollo grid will stop working
There is the theme alteration in front end, but selecting cells or minimizing columns becomes disabled, and user need to re-fresh page

Grid needs to update dark/ light mode normally without need to re-fresh

**Comment by underfisk** [comment]
From what i've seen this issue is the same that happen with the minimize feature, somehow Apollo unsubscribes after your theme change or some other change and does not subscribe them (losing event consumption) therefore useEvent needs to be reviewed and why it is removing the bind after a theme/or any prop change
